apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: development
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    env:
    - name: secret
      valueFrom:
        secretKeyRef:
          name: password
          key: password